version: "3.3"
services:
  auth:
    build:
      context: "${HOOMA_MS_AUTH_BASE_PATH:-$PWD}"
      dockerfile: "./docker/images/auth/Dockerfile"
    image: practice-hooma-auth:latest
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
