version: "3.3"
services:
  auth:
    build:
      context: "${HOOMA_MS_AUTH_BASE_PATH:-$PWD/practice-hooma-ms-auth}"
    environment:
      - DB_PG_PASSWORD_FILE=/run/secrets/db_password
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt_public_key
      - JWT_PRIVATE_KEY_FILE=/run/secrets/jwt_private_key
    secrets:
      - db_password
      - jwt_public_key
      - jwt_private_key
    networks:
      main: { }
      db: { }
